parameters:
    stash.cache.class:      Tedivm\StashBundle\Service\Cache
    stash.handler.class:    Tedivm\Stash\Handler\HandlerInterface
    stash.factory.class:    Tedivm\StashBundle\Factory\HandlerFactory

services:
    stash.cache:
        class:                %stash.cache.class%
        abstract:           true
    stash.handler:
        class:              %stash.handler.class%
        abstract:           true
        synthetic:          true
        factory_method:     createHandler
        factory_class:      %stash.factory.class%
