language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 5.7
    - hhvm

before_install:
    - composer self-update

install:
    - composer install

before_script:
    - Tests/travis/php_setup.sh

script: ./Tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v

matrix:
    fast_finish: true
    allow_failures:
      - php: 5.7
