language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - phpenv config-add tests/php_extensions.ini
    - composer self-update && composer install --dev

script: ./Tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v

matrix:
    allow_failures:
      - php: hhvm